### PR TITLE
Added the contributing guidelines

### PR DESCRIPTION
**Pull request by NefixEstrada**
This is a contributing guidelines suggestion, not the final version.

##### PR details:

* PR type (**Bug Fixing** / **New Feature** / **Enhancement** / **Other?**): Enhancement
* Reference to related issue (issue link): 
* Impact (**Low** / **High** / **Critical** / **Urgent**): Low
* Did you test this PR? 
* Brief description of the changes in this PR: Added the contributing guidelines

### CODE REVIEW

**Comment by NefixEstrada** [comment]
@didacog Yeah, that's the idea.

**Comment by didacog** [comment]
Great! just one question before merging.. The <pre>git flow init</pre> is with all defaults? 
@proura didn't we change any options for our workflow? Sorry I don't remember right now :_(

**Comment by proura** [comment]
@didacog maybe because we have the develop branch as default will need to do the extra step of get the master branch before the ` git flow init`. @NefixEstrada may know it.

**Comment by didacog** [comment]
OK, @NefixEstrada we'll keep the PR open until the gitflow init config steps are clarified, then we can directly merge.

Thanks!

**Comment by didacog** [comment]
@proura  you were talking about this step?

<pre>git checkout -b master origin/master</pre>  before <pre>git flow init</pre>.

The git flow init is all defaults (maybe we can say it in the doc). and I don't know if using forked repo changes somehow the workflow and the need to checkout master branch... ????

**Comment by NefixEstrada** [comment]
You need to specify the *branch name for production releases*:

```sh
[nefix@machine:/tmp/drlm]$ git flow init                                 

Which branch should be used for bringing forth production releases?
   - develop
Branch name for production releases: [] master

Which branch should be used for integration of the "next release"?
   - develop
Branch name for "next release" development: [develop] 

How to name your supporting branch prefixes?
Feature branches? [feature/] 
Bugfix branches? [bugfix/] 
Release branches? [release/] 
Hotfix branches? [hotfix/] 
Support branches? [support/] 
Version tag prefix? [] 
Hooks and filters directory? [/tmp/drlm/.git/hooks] 
```

**Comment by proura** [comment]
Yes, I have also tested and it's what you say, it's only necessary especify the master branch in the `git flow init`

**Pull request merged**
