### PR TITLE
Feature/useful utilities

### PR DESCRIPTION
**Pull request by NefixEstrada**
* PR type (**Bug Fixing** / **New Feature** / **Enhancement** / **Other?**): Enhancement
* Reference to related issue (issue link): 
* Impact (**Low** / **High** / **Critical** / **Urgent**): High
* Did you test this PR? Yes
* Brief description of the changes in this PR:

Added two useful utilites:
 - `listunsched`: list all the clients that don't have scheduled jobs
 - `listbackup -p`: lists the backups and colors the output depending if the backups might have failed

What's missing from this PR?
 - [x] Document the changes
-  [x] Add the options to the bash completions
-  [x] Add options to the configuration to change the colors

### CODE REVIEW

**Comment by proura** [comment]
@krbu I have put you in the reviewers because in this useful utilities feature are some of you DRLM scripts: colored backups list depending on time and size and unscheduled clients. 

@NefixEstrada The times amb sizes used as a threshold must be in the default.conf file. You also need to put the functions (check_backup_time_status, set_color, check_backup_size_status, pretty,...) inside backup-functions.sh. On the other hand, in the feature that list unscheduled clients, I think it would be more appropriate that **listusched** be a listclient (or listjob) parameter than a new workflow. What do you think about it @didacog and @krbu?

**Comment by didacog** [comment]
Hi, Sorry for the late response on the topic.
@proura, yes I prefer something like <pre> listclient --unsched | -U </pre> or, I'm wondering if it could be a column in listclient output like: SCHED (true/false). There is still space for it?

**Comment by NefixEstrada** [comment]
I've moved the command to the default listclient command. It appears as it follows:

```
           
Id     Name            MacAddres       Ip              Client OS       Network         Has Scheduled Jobs
105    ReaRCli1        52540045c755    192.168.50.10                   Isolated        True           
106    RearCliVM       5254000e7a25    192.168.50.15                   Isolated        False          
```

**Comment by didacog** [comment]
Looks better!
I think "Has Scheduled Jobs" is too long for a column header (thinking on standard terminal sizes). Maybe just "Sched" or "Scheduled" is enough??

On the other hand a filter of list all clients for just showing Unscheduled ones:

<pre>drlm listclient [-A] [-U|--unsched]</pre>

**Comment by NefixEstrada** [comment]
@didacog Both changes are in the PR now

**Comment by NefixEstrada** [comment]
@proura Done!

**Pull request merged**
