### PR TITLE
No password login fix

### PR DESCRIPTION
**Pull request by NefixEstrada**
Fix the no password DRLM login feature

### CODE REVIEW

**Comment by didacog** [comment]
Hi,
Does this change take care about files/dirs permissions from root user to drlm user keys? ssh is very restrictive about permissions and if not set properly is going to fail to connect.

**Comment by proura** [comment]
It seems that despite not having the same file permissions it works properly in the tests, but will be better to perform a chmod 600 and chown drlm: to the authorized_keys file to preserve the originals permissions and avoid errors.

**Comment by NefixEstrada** [comment]
It seems that the recommended permissions are:
- `~/.ssh` -> 700
- `~/.ssh/authorized_keys` -> 600

I'm going to add those to ensure that it's going to work properly in all the different distros

**Comment by NefixEstrada** [comment]
Done! Now it changes the permissions and the owner of the required files. Even though I've already done it, you might want to test it to ensure everything works as expected!

**Pull request merged**
