### PR TITLE
Feature/instclient nologin

### PR DESCRIPTION
**Pull request by NefixEstrada**
* PR type (**Bug Fixing** / **New Feature** / **Enhancement** / **Other?**): Enhancement
* Reference to related issue (issue link): 
* Impact (**Low** / **High** / **Critical** / **Urgent**): High
* Did you test this PR? Yes
* Brief description of the changes in this PR: Now during the client installation, DRLM logins to the new client automatically and skips the phase where it asked the "changeme" password.

### CODE REVIEW

**Comment by krbu** [comment]
I've been doing some tests and "-w" option does not exist on RH7 and Centos 7

**Comment by NefixEstrada** [comment]
@krbu could you try again? I added a check and if the distro is CentOS / RedHat, it uses the old `ssh-copy-id` system

**Comment by krbu** [comment]
@NefixEstrada , Sorry , I didn't give you all the info, the problem is with  "setsid -w" the "-w" option does not exist on RH7 and Centos7 .

$  setsid -h                                                                                                                                                                                                              
                                                                                                                                                                                                                                               
Usage:                                                                                                                                                                                                                                         
 setsid [options] <program> [arguments ...]                                                                                                                                                                                                    
                                                                                                                                                                                                                                               
Options:                                                                                                                                                                                                                                       
 -c, --ctty     set the controlling terminal to the current one                                                                                                                                                                                
 -h, --help     display this help and exit                                                                                                                                                                                                     
 -V, --version  output version information and exit

**Comment by proura** [comment]
@NefixEstrada there is no other way to solve this? other commands, app, ... Imo introduce different behaviors depending on the GNU/Linux distribution can create confusion and make it difficult to use.

**Comment by NefixEstrada** [comment]
I totally agree with you. It also makes it more difficult for debugging. The thing is that I haven't found any other reliable way to do it without adding extra dependencies

**Comment by NefixEstrada** [comment]
I've been doing some research on which could be the best solution. It seems that we don't have other option than adding `sshpass` as a dependency to ensure the consistency between the different distributions.

It seems that all the supported server distributions have the package available (you can check it [here](https://pkgs.org/download/sshpass)). What do you think?

**Comment by proura** [comment]
If this is only to skip inserting the "changeme" password when the **ssh-copy-id** command is called why we don't copy the key manualy into the ~/.ssh/authorized_keys file?

**Comment by proura** [comment]
It's ok for me! Assuming you have test it.

**Pull request merged**
